"""initial schema

Revision ID: 0e9c71e767a7
Revises: 
Create Date: 2026-09-29 20:00:40.043705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9c71e767a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_token_hash', sa.String(length=64), nullable=False),
    sa.Column('manage_token_hash', sa.String(length=64), nullable=False),
    sa.Column('destination_email', sa.String(length=320), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_token_hash', sa.String(length=64), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('permanent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token_hash')
    )
    op.create_index(op.f('ix_endpoints_manage_token_hash'), 'endpoints', ['manage_token_hash'], unique=True)
    op.create_index(op.f('ix_endpoints_public_token_hash'), 'endpoints', ['public_token_hash'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('sender_name', sa.String(length=200), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('extra_fields', sa.JSON(), nullable=False),
    sa.Column('forwarded_at', sa.DateTime(), nullable=True),
    sa.Column('forward_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_endpoint_id'), 'submissions', ['endpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_endpoint_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_endpoints_public_token_hash'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_manage_token_hash'), table_name='endpoints')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
