"""add endpoint origin

Revision ID: cf02a60af8c6
Revises: 0e9c71e767a7
Create Date: 2026-09-30 16:01:59.971800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf02a60af8c6'
down_revision: Union[str, Sequence[str], None] = '0e9c71e767a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('origin', sa.String(length=253), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'origin')
    # ### end Alembic commands ###
